version: '3.8'

services:
  app:
    build: .
    container_name: job_search_app
    ports:
      - "8000:8000"  # FastAPI (or Flask) app
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
      - JOB_SEARCH_API_URL=${JOB_SEARCH_API_URL}
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app
    networks:
      - job_search_network

  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - job_search_network

  redis:
    image: redis:6
    container_name: redis
    networks:
      - job_search_network

volumes:
  postgres_data:

networks:
  job_search_network:
    driver: bridge
